# -*- coding: utf-8 -*-

"""
   apimaticcalculatortestcaseslib.configuration

   This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/05/2017
"""
from .api_helper import APIHelper

class Configuration(object):

    """A class used for configuring the SDK by a user.
    
    This class need not be instantiated and all properties and methods
	are accessible without instance creation.
    
    """

    # The base Uri for API calls
    base_uri = 'http://examples.apimatic.io/apps/calculator'

    # The username to use with basic authentication
    # TODO: Set an appropriate value
    basic_auth_user_name = "TODO: Replace"

    # The password to use with basic authentication
    # TODO: Set an appropriate value
    basic_auth_password = "TODO: Replace"


